scalar GraphQLDate

type Book {
	title: String!
	author: Author
	publisher: String
	publishDate: GraphQLDate
	price: Float!
}

type Author {
	name: String!
	age: Int
}

input inputAuthor {
	name: String!
	age: Int
}

# Queries and Mutations

type Query {
	books: [Book]
}

type Mutation {
	addBook(
		title: String!
		author: inputAuthor!
		publisher: String
		publishDate: GraphQLDate
		price: Float!
	): Book
}
