scalar GraphQLDate

type Book {
	id: ID!
	title: String
	author: Author
	publisher: String
	publishDate: GraphQLDate
	price: Float!
}

type Author {
	name: String!
	age: Int
}

input inputAuthor {
	name: String!
	age: Int
}

input updateBook {
	id: ID!
	title: String
	author: inputAuthor
	publisher: String
	publishDate: GraphQLDate
	price: Float
}

# Queries and Mutations

type Query {
	books: [Book]
}

type Mutation {
	addBook(
		title: String!
		author: inputAuthor!
		publisher: String
		publishDate: GraphQLDate
		price: Float!
	): Book

	updateBook(book: updateBook!): Book
}
